module.exports = {
  apps: [
    {
      name: 'mlx-load-balancer',
      script: 'optimized_load_balancer.py',
      args: '--config config.json --port 8090',
      interpreter: 'python3',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PYTHONPATH: '.',
        MLX_GPU_MEMORY_FRACTION: '0.85',
      },
      log_file: 'logs/mlx-load-balancer.log',
      error_file: 'logs/mlx-load-balancer-error.log',
      out_file: 'logs/mlx-load-balancer-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 5,
      min_uptime: '10s',
      max_memory_restart: '1G',
    },
    {
      name: 'mlx-server-manager',
      script: 'enhanced_server_manager.py',
      interpreter: 'python3',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PYTHONPATH: '.',
        MLX_GPU_MEMORY_FRACTION: '0.85',
      },
      log_file: 'logs/mlx-server-manager.log',
      error_file: 'logs/mlx-server-manager-error.log',
      out_file: 'logs/mlx-server-manager-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 3,
      min_uptime: '30s',
      max_memory_restart: '2G',
    },
    {
      name: 'mcp-server',
      script: '../mcp-server/dist/index.js',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      log_file: 'logs/mcp-server.log',
      error_file: 'logs/mcp-server-error.log',
      out_file: 'logs/mcp-server-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_restarts: 5,
      min_uptime: '10s',
      max_memory_restart: '512M',
    },
  ],
};